### ISSUE TITLE
Do not break octals

### ISSUE THREAD

**Issue by sanmai-NL** [pascalre/vscode-yaml-sort#118]
[`vscode-yaml-sort`](https://github.com/pascalre/vscode-yaml-sort) replaces `0644` with `644`. 0644 is a different number in the octal system than 644 is in the decimal system. This transformation defect can break e.g., Kubernetes manifests.

Please see: https://github.com/projectcontour/contour/issues/5030.

**Comment by pascalre** [comment]
Hello @sanmai-NL, thank you for this feature request. The extension uses the library [js-yaml](https://github.com/nodeca/js-yaml) which causes this behavior. You can check it on their [online parser](https://nodeca.github.io/js-yaml/). So please open an issues for this on the js-yaml project.

In the meantime I will have thoughts on how I can solve it in this extension.

**Comment by pascalre** [comment]
Hello @sanmai-NL please check out version 6.3.0, it contains an "OctalProcessor" which will protect octal values from being malformed. If you got any issues with that, let me know.
If you like this extension please support my work and leave a review on the [marketplace](https://marketplace.visualstudio.com/items?itemName=PascalReitermann93.vscode-yaml-sort&ssr=false#review-details).
