### ISSUE TITLE
YAML with HTML tags breaks in v6.5.0

### ISSUE THREAD

**Issue by utilityboy** [pascalre/vscode-yaml-sort#126]
Hello.

We found an issue with the latest release whereby any yaml file with HTML tags in content will cause all keys to be deleted upon sort:

Given:
```
---
token_label: this is a {token}
html_label: this is <span>html</span>
1_label: foo
2_label:
  2_1_label: bar
  2_2_label: baz
```

Validate YAML -> OK

Sort YAML -> Empty File
<img width="479" alt="image" src="https://user-images.githubusercontent.com/130537/225956648-1606fa1d-e7d7-46a1-a32a-af8a9a96842c.png">

Quoting (single or double) of `html_label` has no effect.  Removing the `span` tags produces the expected results:
```
---
1_label: foo
2_label:
  2_1_label: bar
  2_2_label: baz
html_label: this is html
token_label: this is a {token}
```

Thanks for the great extension!

**Comment by pascalre** [comment]
@utilityboy this is some issue in the BlockProcessor. Until I fixed it, you can turn the BlockProcessor off, by setting:
```
 "vscode-yaml-sort.useBlockProcessor": false
```

**Comment by marcospgp** [comment]
I am getting the same issue when trying to sort a GitHub actions workflow file, but there's no HTML. Maybe it's the templating that is causing it, such as `some_value: ${{ inputs.BUILD_URL }}`?

**Comment by johanla0** [comment]
Same thing, confirmed

**Comment by pascalre** [comment]
@marcospgp what is this for a templating language? It looks like helm, but I never saw the dollar sign before the curly brackets before.

**Comment by marcospgp** [comment]
@pascalre GitHub actions/workflows

**Comment by pascalre** [comment]
@utilityboy I just bumped 6.5.1 can you please verify the issue is solved?
