### ISSUE TITLE
Value type may not be maintained: Unexpected String to Int conversion

### ISSUE THREAD

**Issue by afischer-opentext-com** [pascalre/vscode-yaml-sort#128]
## Description

Assuming the following yaml

```(yaml)
---
bar: 1234567890123
foo: "1234567890123"
baz: "123456789012"
```

The result is

```(yaml)
---
bar: 1234567890123
baz: '123456789012'
foo: 1234567890123
```

Note the different type of the `foo` value but the same type of the `baz` value.

##  Expected behavior

Value of key `foo` is of type String after sorting. Avoid special handling for strings longer than 11 characters whose content is only numbers.

**Comment by pascalre** [comment]
Hi @afischer-opentext-com, I fixed a lot of bugs in the last weeks. In the latest version (6.5.9) I cannot confirm your issue. I assume it is solved in the meanwhile. If not, feel free to open this issue again.
