### ISSUE TITLE
[bug] sort drops value from key, when key in custom sort list

### ISSUE THREAD

**Issue by diepes** [pascalre/vscode-yaml-sort#13]
Sorting snippet below with Custom sort list, where "proxyext_urls" is in custom list, looses the "b"

```
##Start
proxyext_urls:
  - aa: "b" #6631
test2: ok
##End
```
ctrl+shift+p
custom sort 3

>> results in 
```
proxyext_urls:
  - aa: 
test2: ok
```

**Comment by pascalre** [comment]
@diepes please check out version 2.3.2 of this extension which fixes this issue
