### ISSUE TITLE
Entire spec is deleted

### ISSUE THREAD

**Issue by devhl-labs** [pascalre/vscode-yaml-sort#148]
Sorting this yaml https://raw.githubusercontent.com/devhl-labs/Clash-of-Clans-Swagger/master/swagger-source.yml deletes all of the spec. There is a toast notification the following. 

bad indentation of a mapping entry (5:555) 2 | ... 3 | ... 4 | ... 5 | ... rization header looks like this: "Authorization: Bearer API_TOKEN". -----------------------------------------^ 6 | ... 7 | ..

![image](https://github.com/pascalre/vscode-yaml-sort/assets/29644329/1e101674-5cc4-476d-ba06-c81b7ef3f150)

**Comment by pascalre** [comment]
Hello @devhl-labs I fixed a lot of bugs in the last weeks. In the latest version (6.5.9) I cannot confirm your issue. I assume it is solved in the meanwhile. If not, feel free to open this issue again.
