### ISSUE TITLE
Unable to sort a multi document yaml file

### ISSUE THREAD

**Issue by chrisliness** [pascalre/vscode-yaml-sort#16]
This feature use to work on previous versions however it seems to be broken now.

VSCode error -> YAML is invalid: expected a single document in the stream, but found more

Plugin Version: v2.7.1 (rolling back to v2.6.0 worked fine)
Example yaml: 

[example.yml.txt](https://github.com/pascalre/vscode-yaml-sort/files/5465235/example.yml.txt)

**Comment by pascalre** [comment]
Hello @chrisliness I will be working on this issue ASAP

**Comment by chrisliness** [comment]
Thanks for fixing.
