### ISSUE TITLE
Comment processor duplicates comments inside block scalars

### ISSUE THREAD

**Issue by fossrob** [pascalre/vscode-yaml-sort#164]
Firstly thank you for this extension! 🫶🏻  It's incredibly useful!

One issue to report regarding arrays of block scalars and comments:

Example before:
```yaml
block:
  - |
    # comment 1
    some command
    # comment 2
    some other command
```

Example after sorting once:
```yaml
block:
  - |
    # comment 1
    # comment 1
    some command
    # comment 2
    # comment 2
    some other command

```

Example after sorting twice:
```yaml
block:
  - |
    # comment 1
    # comment 1
    # comment 1
    # comment 1
    some command
    # comment 2
    # comment 2
    # comment 2
    # comment 2
    some other command

```

This is with the latest version of vscode and the extension.

**Comment by pascalre** [comment]
Thanks for this issue, I solved it with [cd793e4](https://github.com/pascalre/vscode-yaml-sort/commit/cd793e478630d1f61a28c236eae5988e936eef52). It will be available with the next release. If you like this extension, please support my work by giving this extension a good review on the [marketplace](https://marketplace.visualstudio.com/items?itemName=PascalReitermann93.vscode-yaml-sort&ssr=false#review-details).
