### ISSUE TITLE
question: after format , results changed in an odd manner

### ISSUE THREAD

**Issue by JWleo** [pascalre/vscode-yaml-sort#175]
before format:
![before](https://github.com/pascalre/vscode-yaml-sort/assets/32316654/230a5caa-eb80-411c-a7b8-cca4a23ab892)

after format:
![after](https://github.com/pascalre/vscode-yaml-sort/assets/32316654/b3e9c204-4d2b-434f-88cc-43920a7018c5)

why did happen like this?  is  the word of "y" special ?

**Comment by pascalre** [comment]
The chars `y` and `n` represent boolean values. You can avoid this behavior by setting:
```
"vscode-yaml-sort.noCompatMode": true
```
