### ISSUE TITLE
Sort all files in directory

### ISSUE THREAD

**Issue by freeseacher** [pascalre/vscode-yaml-sort#2]
I was found plugin usefull but found that i'm stuck in that workflow
open file press ctrl+shift+p select most last used command and press enter. 
i was tied to do this on 5-th file and i got much more then thousand. 

can you please add option on directory level in left menu to sort all files in directory

**Comment by pascalre** [comment]
Hi @freeseacher I think it's very hard to implement this, I don't even know if there is an API to see on which folder in the menu the click was executed. When I got some time I can try to add this option. Feel free to contribute.
