### ISSUE TITLE
Add new line after 2nd/Nth level key

### ISSUE THREAD

**Issue by rswrz** [pascalre/vscode-yaml-sort#21]
First of all, thanks for this great extension. I'm using this to sort my AWS CloudFormation Stacks.

For a better readability of big files it would be great to add empty lines after second-level keys, too - like `vscode-yaml-sort.addNewLineAfterTopLevelKey` does for first level. Maybe it could be even possible to configure with an `int` value until which level a new line will be added.

**Comment by pascalre** [comment]
@rswrz I just released version 3.0.0 which supports the setting `emptyLinesUntilLevel`. When you set this two `2` there will be added new lines before all keywords on level 2.
If you like this extension, I really would be happy about a rating on the marketplace.
