### ISSUE TITLE
Is it possible to apply sorting to ALL selected files? 

### ISSUE THREAD

**Issue by Me1kaa** [pascalre/vscode-yaml-sort#22]
Hello! I have a big project, with about 100+ YAML files, and need to sort them all, is it possible to do with a plugin?

**Comment by pascalre** [comment]
Hello @Me1kaa currently this is not possible to do with the plugin. The issue [2](https://github.com/pascalre/vscode-yaml-sort/issues/2) already requested this feature. I will reopen the old issue and will consider working on it.

**Comment by Me1kaa** [comment]
@pascalre Thank you for your answer. Will be waiting for that issue is ready.

**Comment by pascalre** [comment]
@Me1kaa version 3.1.0 can sort all yaml files in a directory.
