### ISSUE TITLE
CloudFormation Friendly

### ISSUE THREAD

**Issue by robbrad** [pascalre/vscode-yaml-sort#23]
What a great extension !

I would like the ability to sort AWS CloudFromation YAML e.g. https://raw.githubusercontent.com/awslabs/aws-cloudformation-templates/master/aws/solutions/CloudFrontCustomOriginLambda%40Edge/CloudFront.yaml

At the moment the Extension throws an error due to !Sub / !Join / !Ref Cloudformation functions - with Invalid Yaml (Maybe this validation could omit the validity check?)

What would also be VERY nice if it was possible to group Yaml blocks based on linkages used by the !Ref or !Sub

Consider two yaml blocks at the same level feature would be IAM role is put next to an IAM policy because there is a !Ref marker to the IAM role in the IAM policy.

**Comment by pascalre** [comment]
With version 3.2.0 I added the option to configure a `scheme`. I will expand this setting, so that you can use a CloudFormation schema.

**Comment by pascalre** [comment]
@robbrad in version 3.3.0 it is possible to set `scheme` to `CLOUDFORMATION_SCHEMA`. This will support Cloudformation functions and will not break on yaml validation. But be careful: The yaml which you posted contains references. As I already mentioned in the [Readme](https://github.com/pascalre/vscode-yaml-sort/blob/master/README.md#known-problems) references are not working in this extension.

**Comment by robbrad** [comment]
Amazing work! Thanks man!!
