### ISSUE TITLE
Unexpected date string format

### ISSUE THREAD

**Issue by rswrz** [pascalre/vscode-yaml-sort#24]
Hi and thanks again for this great extension.

I found out that a simple unquoted date string will be formatted into ISO 8601 Date and time string.

```yaml
AWSTemplateFormatVersion: 2010-09-09
```
becomes
```yaml
AWSTemplateFormatVersion: 2010-09-09T00:00:00.000Z
```
Is this a bug or a feature? My expected behavior is to keep the short date string even when unquoted.

**Comment by pascalre** [comment]
In version 3.2.0 I added the setting `schema` with the default of `DEFAULT_SCHEMA`. You can set this to `CORE_SCHEMA` and this will solve your problems.
But anyway you should consider treating your dates as string and set the type either explicit or implicit (using quotes):
```
explicit: !!str 2010-09-09
implicit: '2010-09-09'
```
