### ISSUE TITLE
Sort using localeCompare

### ISSUE THREAD

**Issue by EspadaV8** [pascalre/vscode-yaml-sort#25]
The sorting at the moment doesn't sort how you would normally expect strings to be sorted, e.g. in my YAML file I have `completedDate` and `completeTask` however, `completeTask` is sorted first because the `T` appears to come first compared to the `d`. This isn't how people would normally expect these to be sorted.

I think updating the sorting to `return a.localeCompare(b, locale)` would result in a more human expected sorting order. It would be great if this could be the default, although I expect that would break a number of existing files, so perhaps it would be possible to have this as a configuration option along with the locale to use for the sorting (possibly defaulting to `'en'` since I expect that would be the largest part of the userbase).

**Comment by pascalre** [comment]
@EspadaV8 I already knew about this behavior and yeah I think using `localCompare` will definitely be the better sorting algorithm. This feature will result in a new major version, since this is a breaking change in the main functionality. The configuration `locale` will let the user choose which locale to use.

**Comment by EspadaV8** [comment]
That's fantastic. Thank you 🙂

**Comment by EspadaV8** [comment]
I've just updated the extension but it doesn't seem to be sorting any differently. Not sure what's going on :thinking:

**Comment by EspadaV8** [comment]
Ahh, I've been using the `Sort YAML` command which seems to use the "normal" sorting method instead of using one of the `Custom Sort X` commands. It could be useful to prefix those with `YAML` since I only found out about those whilst looking through to code to see what was going on.
