### ISSUE TITLE
Not handling helm chart values references.

### ISSUE THREAD

**Issue by TayBill** [pascalre/vscode-yaml-sort#27]
Consider this snippet:
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  labels:
    app: clientsso
  name:  {{ .Values.ui.environment.keycloakClientId }}
  namespace:  {{ required "Keycloak namespace required" .Values.keycloak.namespace }}

If I use yamlsort on it, I get this:
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  labels:
    app: clientsso
  name:
    '[object Object]': null <<<<<<<<<<<<<<<<<
  namespace:
    '[object Object]': null <<<<<<<<<<<<<<<<<

Note that the values for name and namespace have been modified.
Is there a workaround?

**Comment by pascalre** [comment]
@TayBill this is an issue on the `js-yaml` library which is used in this project. I opened an [issue](https://github.com/nodeca/js-yaml/issues/620) on the project.
