### ISSUE TITLE
Use as formatter

### ISSUE THREAD

**Issue by Timmitry** [pascalre/vscode-yaml-sort#30]
I wonder if it's possible to register this extension as a formatter for yaml files? When I'm in a .yml file in VSCode and run "Format Document", it tells me `There is no formatter for 'yaml' files installed.`. 

Having this wonderful extension as a formatter would also allow me to configure that it auto-formats on save 🙃

**Comment by pascalre** [comment]
Hey @Timmitry I just released version 4.2.0 which can be used as a formatter. You can format your files with the built in formatting shortcuts or just configure auto-format on save.
If you enjoy this extension I really would appreciate a rating on the Visual Studio Code Marketplace.

**Comment by Timmitry** [comment]
@pascalre Nice, thanks a lot! Just tested it, works like a charm 👍 And I was glad to write my first rating ever in the marketplace for you ⭐⭐⭐⭐⭐

**Comment by pascalre** [comment]
Hello @Timmitry,
in version 5.0.0 the yaml formatter is now disabled by default. If you need to enable the formatter, you can set the configuration `useAsFormatter` to `true`.
