### ISSUE TITLE
Add 'newLine' at end of file option

### ISSUE THREAD

**Issue by jorneilander** [pascalre/vscode-yaml-sort#31]
Some coding conventions say that a newline must always be present at the end of a file. Sorting a YAML-file now removes any newlines, including the one at the end. Can it be made optional to add it?

**Comment by Timmitry** [comment]
@jorneilander At least as a workaround: I have configured the setting `"files.insertFinalNewline": true`, which always adds a newline when saving a document. This way, I never even noticed that this extension removes the final newline 🙃

**Comment by pascalre** [comment]
@jorneilander I recommend using the solution @Timmitry proposed. Visual Studio Code already offers this configuration, so there is no need to implement it.
