### ISSUE TITLE
Make formatter configurable

### ISSUE THREAD

**Issue by ppuschmann** [pascalre/vscode-yaml-sort#34]
Hi,

the automatic formatting of YAML-files is a great feature.
Working a lot with Ansible, there's YAML all over the place.

Unfortunately the updated plugin now "aggressively" removes empty lines,
quotes and curly-braces. (I guess the change was #30 )

Often it is a good idea to remove useless characters like quotes and curly-braces, I agree.
I think it would be nice to have these "cleanup" configurable or executable as a separate command.

Currently I disabled the extension completely because
- I have too many changes in my files
- I no longer can read / structure my files because of deleted empty lines

**Comment by pascalre** [comment]
Hi @ppuschmann please update to version 5.0.0. The yaml formatter is now disabled by default. If you need to enable the formatter, you can use the configuration `useAsFormatter`.
