### ISSUE TITLE
emptyLinesUntilLevel doesn't work with keywords containing dashes

### ISSUE THREAD

**Issue by Dulanic** [pascalre/vscode-yaml-sort#35]
Hello,

Love the extension! However, I have found it is not always consistent /w the emptyLinesUntilLevel settings. I haven't been able to identify the root cause thus far. I used this for sort my yaml and you can see how it is missing the nested line breaks on lines 33, 247, and 390.

Here is my yaml file:

https://github.com/Dulanic/docker-compose/blob/main/docker-compose.yml

These are my settings:
```

    "vscode-yaml-sort.customSortKeywords_1": [
        "version",
        "services",
        "container_name",
        "image",
        "user",
        "depends_on",
        "enviroment",
        "env_file",
        "shm_size",
        "hostname",
        "ports",
        "volumes",
        "restart",
        "volumes",
        "command",
        "health_check"
    ],
    "vscode-yaml-sort.useAsFormatter": true,
    "vscode-yaml-sort.emptyLinesUntilLevel": 2,
    "vscode-yaml-sort.quotingType": "\"",
    "vscode-yaml-sort.forceQuotes": true,
```

**Comment by pascalre** [comment]
@Dulanic latest version 5.0.1 contains the fix.
If you like this extension, please consider a rating on the [marketplace](https://marketplace.visualstudio.com/items?itemName=PascalReitermann93.vscode-yaml-sort&ssr=false#review-details). This will support my work.

**Comment by Dulanic** [comment]
Thanks! I will do that.
