### ISSUE TITLE
Add support for single line arrays

### ISSUE THREAD

**Issue by Dulanic** [pascalre/vscode-yaml-sort#36]
Is it possible to avoid line brakes for specific keys? EX: I use health checks sometimes in docker compose, and it makes it look kind of messy /w it breaking out the array. I'd like to have the ability to exclode for example below... test.

EX:
`test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]`
becomes
```
      test:
        - "CMD"
        - "pg_isready"
        - "-q"
        - "-d"
        - "${DB_NAME}"
        - "-U"
        - "${DB_USER}"
```

**Comment by huxuan** [comment]
+1, in certain circumstance, it is wired to break the array into multi-line pattern. Maybe it is better to support both multi-line and single-line and keep as it is?
