### ISSUE TITLE
YAML comments are being deleted

### ISSUE THREAD

**Issue by mchelen-gov** [pascalre/vscode-yaml-sort#39]
```yaml
test:
# comment
- foo
- bar
```

run `>YAML Sort: Sort YAML`

`#comment` gets deleted

**Comment by pascalre** [comment]
@mchelen-gov already [mentioned](https://github.com/pascalre/vscode-yaml-sort/issues/4), the js-yaml library which is used for sorting does not keep comments when sorting.

**Comment by schlomo** [comment]
For those who need YAML sorting with comments on top: Selecting the actual YAML without the comments and then sorting it works as only the selection is sent through the sorter.

Can I add a simple suggestion to @mchelen-gov and @pascalre: This extension could automatically detect the comments on top and then send only the YAML after the comments to the sorter, thereby preserving at least comments on top.
