### ISSUE TITLE
Keep comments in the yaml file

### ISSUE THREAD

**Issue by tianmiaohu-fis** [pascalre/vscode-yaml-sort#45]
The tool removes all comments in the yaml file.  Please keep the comments and if possible, provide an option (sticky comment) where the comment won't be sorted and stay with the non-comment line below.

**Comment by nburkecogito** [comment]
I came to report this -- This is, imho, a pretty big issue for us YAML engineers, I would rather have helpful comments than sorted YAML.

**Comment by bslpzk** [comment]
The add-on is great, I use it every day - many thanks to Pascal. But the giant problem is the comments, or rather the absence of them after sorting. Many people work on the code and these comments are crucial.
If it were possible to link a comment to the line below it or to the line at the top, and after sorting, it would help a lot.
The same thing could be done with comments at the end of lines - do these comments somehow prevent sorting?

**Comment by pascalre** [comment]
I added this feature to version 5.4.2. Please try if it fits your need. If you like this extension, I would really appreciate a good review on the [marketplace](https://marketplace.visualstudio.com/items?itemName=PascalReitermann93.vscode-yaml-sort&ssr=false#review-details).

**Comment by tianmiaohu-fis** [comment]
There are still issues with comments.  Try the below yaml content.  The second comment disappears after sorting.
#begin comment
params:
  logon: test
  #variable meta data
  variableMetadata: env\config_dev.yaml
  logFile: log-test.log
  logLevel: DEBUG
  chunkSize: 1000
  jobSize: 20
  schema: test
  #end comment

**Comment by pascalre** [comment]
@tianmiaohu-fis just released 6.0.3 which fixes your problem. Please check it out. If there are still issues please report them in a new GitHub issue.
