### ISSUE TITLE
Allow for configuration of line length

### ISSUE THREAD

**Issue by utilityboy** [pascalre/vscode-yaml-sort#5]
Thanks for the extension. I've kept Atom around specifically to sort a few files.

Would you consider either defaulting to a long line length on sort ( > 500), or potentially adding a configuration point for it?

```
    let sorted_yaml = yaml_parser.safeDump(doc, {
      sortKeys: true,
      lineWidth: config.lineWidth
    });
```

I'm happy to work up a PR for it, though I've never authored an extension so I'm not sure what's involved.

**Comment by pascalre** [comment]
@utilityboy thanks for this issue. It was just a small change so I quickly fixed this on my own. Feel free to update to 1.1.0

**Comment by utilityboy** [comment]
That's great @pascalre. Thanks so much!
