### ISSUE TITLE
sort removed block/folded string style

### ISSUE THREAD

**Issue by gutenye** [pascalre/vscode-yaml-sort#62]
Sort this file

```yaml
hello: |-
  World
```

Result into

```yaml
hello: World
```

Exepcted

```yaml
hello: |-
  World
```

Is there a way to keep `|-`? [yq](https://github.com/mikefarah/yq) works fine

**Comment by pascalre** [comment]
Supported in version 6.5.0. If you like this extension, please consider leaving a review on the visual studio code marketplace.
