### ISSUE TITLE
No need to send notification when used as a formatter

### ISSUE THREAD

**Issue by longkai** [pascalre/vscode-yaml-sort#65]
I found the extension will notify when sort, validate, and format.

As other language's default formatters, when something is done successfully, there is no notification except bad things happened.

This is make sense for such a tool.

**Comment by pascalre** [comment]
@longkai issue is solved in version 5.5.0. If you like this extension, I would be really grateful if you leave a positive review on the [marketplace](https://marketplace.visualstudio.com/items?itemName=PascalReitermann93.vscode-yaml-sort&ssr=false#review-details)
