### ISSUE TITLE
Keys could not be resorted: expected a single document in the stream, but found more

### ISSUE THREAD

**Issue by prokher** [pascalre/vscode-yaml-sort#7]
Unfortunately, this plugin does not support YAML-documents with several YAMLs inside separated by `---`. It is quite typical to have several Kubernetes manifests in a single YAML-file. For example, we have a lot of manifests with both `kind: Service` & `kind: Deployment` inside. Plugin does not work on these files. It would be nice to support this kind of files.

**Comment by pascalre** [comment]
@prokher I like this issue. It would definitely be a nice thing to support such files. It does not seem to be a big change in the code. I will work on this, when I got some time.

**Comment by pascalre** [comment]
@prokher please update to version 1.3.0. Problem should be solved.

**Comment by prokher** [comment]
Thank you for the update. It now adds extra `---` to the beginning to each sorted file, even if there is only one document inside.

**Comment by pascalre** [comment]
I added the setting “vscode-yaml-sort.useLeadingDashes„ with a default value of „true“. You can change this to „false“ to avoid the leading dashes.
